apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::528037940015:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7URFOSG5ZCYE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::528037940015:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T07:58:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1347"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 48b7c46f-752b-4f66-bfba-f4759c878868
